application: youtube-antishit-userscript
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /stylesheets
  static_dir: stylesheets

- url: /.*.user.js
  script: _go_app
